AllCops:
  TargetRubyVersion: 2.6.5

Layout/LineLength:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false
  
Style/HashTransformValues:
  Enabled: false